#! /bin/sh
# . "${HOME}/.cache/wal/colors.sh"

export QT_QPA_PLATFORMTHEME=qt5ct
export AWT_TOOLKIT=MToolkit

sxhkd &
wmname compiz &

# xrandr --output DVI-I-0 --auto
bspc monitor -d I II III IV V VI

bspc config normal_border_color  "#0F244E"
# bspc config focused_border_color "$color6"

bspc config border_width         1
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config top_padding			 30
bspc config left_padding		 0
bspc config right_padding		 0
bspc config bottom_padding		 0

bspc rule -a albert border=off
bspc rule -a albert_hack state=floating border=off
bspc rule -a firefox desktop='II'
bspc rule -a code desktop='I'
bspc rule -a subl desktop='III'
bspc rule -a discord desktop='VI'
bspc rule -a spotify desktop='VI'
bspc rule -a ferdi desktop='V'

# feh --no-fehbg --bg-fill $wallpaper &
# ~/.config/polybar/launch.sh &

# killall stw
# stw -x 585 -y 430 -F 'Iosevka:size=64' -f "#ffffff" -A 00 date +%R &

xsetroot -cursor_name left_ptr &
xautolock -detectsleep -time 15 -locker "betterlockscreen -l" &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# dunst &
killall clipit
clipit &
picom --experimental-backends &
playerctld daemon &
flameshot &
discord --start-minimized &
albert &

~/.config/wal/apply.sh
~/.config/polybar/launch.sh

while sleep 1200; do ~/.config/wal/apply.sh; done
